# Generated by Django 4.1.4 on 2023-01-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0005_aboutsection_myskills_whychooseu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Phonenumber', models.CharField(max_length=20)),
                ('Subject', models.CharField(choices=[('seo', 'SEO'), ('WebDesign', 'WEBDESIGN'), ('Graphice Designing', 'GRAPHICSDESIGNING'), ('SocialMediaMarketing', 'SOCIALMEDIAMARKETING'), ('WebDevelopment', 'WEBDEVELOPMENT'), ('EmailMarketing', 'EMAILMARKETING'), ('ADsManagement', 'ADMANAGEMENT'), ('Animations', 'ANIMATIONS')], max_length=100)),
                ('Message', models.CharField(max_length=400)),
            ],
        ),
    ]
