# Generated by Django 4.1.4 on 2023-01-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0006_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('title2', models.TextField(max_length=50)),
                ('item1', models.TextField(max_length=20)),
                ('item2', models.TextField(max_length=20)),
                ('item3', models.TextField(max_length=20)),
                ('item4', models.TextField(max_length=20)),
                ('item5', models.TextField(max_length=20)),
                ('item6', models.TextField(max_length=20)),
                ('title3', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('copyright', models.TextField(max_length=200)),
            ],
        ),
    ]
