# Generated by Django 4.1.4 on 2023-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novoapp', '0008_clientslogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientlightLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='allimages')),
            ],
        ),
    ]
